### ISSUE TITLE
Valid type list is missing SpatialRecursivePrefixTreeFieldType

### ISSUE THREAD

**Issue by arafalov** [tow/sunburnt#91]
Introduced in Solr 4.0 and is used in [the example schema](https://github.com/apache/lucene-solr/blob/lucene_solr_4_0_0/solr/example/solr/collection1/conf/schema.xml#L688) since.

Exception caused:

```
Traceback (most recent call last):
  File "/Users/arafalov/Projects/solr-client-book/code/PythonClients/sunburntClient/test.py", line 5, in <module>
    solr_interface = sunburnt.SolrInterface("http://localhost:8983/solr/")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sunburnt/sunburnt.py", line 153, in __init__
    self.init_schema()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sunburnt/sunburnt.py", line 164, in init_schema
    self.schema = SolrSchema(schemadoc)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sunburnt/schema.py", line 394, in __init__
    = self.schema_parse(f)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sunburnt/schema.py", line 414, in schema_parse
    name, field_type_class = self.field_type_factory(field_type_node)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sunburnt/schema.py", line 442, in field_type_factory
    raise SolrError("Unknown field_class '%s'" % class_name)
sunburnt.schema.SolrError: Unknown field_class 'solr.SpatialRecursivePrefixTreeFieldType'
```

**Comment by cryptid11** [comment]
I got this
Traceback (most recent call last):
  File "solr.py", line 87, in <module>
    si.add(document)
  File "/usr/lib/python2.7/site-packages/sunburnt/sunburnt.py", line 174, in add
    update_message = self.schema.make_update(doc_chunk)
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 504, in make_update
    return SolrUpdate(self, docs)
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 535, in __init__
    self.xml = self.add(docs)
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 564, in add
    return self.ADD(*[self.doc(doc) for doc in docs])
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 555, in doc
    for name, values in doc.items()]))
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 541, in fields
    field_values = [self.schema.field_from_user_data(name, value) for value in values]
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 501, in field_from_user_data
    return field.instance_from_user_data(v)
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 146, in instance_from_user_data
    return SolrFieldInstance.from_user_data(self, data)
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 333, in from_user_data
    self.value = self.field.from_user_data(data)
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 152, in from_user_data
    return self.normalize(value)
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 258, in normalize
    return solr_date(v)
  File "/usr/lib/python2.7/site-packages/sunburnt/schema.py", line 37, in __init__
    self._dt_obj = datetime_from_w3_datestring(v)
  File "/usr/lib/python2.7/site-packages/sunburnt/dates.py", line 61, in datetime_from_w3_datestring
    raise ValueError(e.args[0])
NameError: global name 'e' is not defined


After updating fedora21, lat time I use it it works...
